### ISSUE TITLE
Monitor all remotes of a local repository

### ISSUE THREAD

**Issue by nbedos** [nbedos/citop#3]
From https://github.com/nbedos/citop/issues/2#issuecomment-567583923

> Thanks for the quick response. I have a project that exists both on gitlab.com and a private gitlab instance and my local git repo is configured with two remotes pointing to both of them. I am now running citop 0.1.1 and have both `[[providers.gitlab]]` sections defined in citop.toml. When on a branch that has been pushed to both instances, running `citop` only shows the gitlab.com pipeline corresponding to the current commit; this persists even when I swap the order of gitlab provider definitions in the config. If I run `citop -r url_to_private_gitlab_repo` then I see the pipeline corresponding to the current commit on the private gitlab instance.
> 
> I expected to see both the gitlab.com and private gitlab instance pipelines when running `citop` without arguments, do you consider this expected behaviour reasonable?

Currently `citop` supports monitoring just one repository:

* When running `citop`, the repository monitored is the one associated to the remote named `origin` of the current git repository
* When running `citop -r <URL>`, only a single URL is accepted

It would be desirable to monitor all the remotes of a local repository ~~and accept multiple URLs on the command line~~.

**Comment by nbedos** [comment]
@aboyett :  Would you mind giving a try to [version 0.1.3rc0](https://github.com/nbedos/citop/releases/tag/0.1.3rc0)? You should now see the pipelines of all the remotes of your repository.

I didn't change the command line interface to accept multiple URLs as I mentioned in the first message of this issue since it's a little more complicated (When running `citop -r URL1 URL2 master`, master might refer to a different commit for each repository. This can not happen when working with a local repository with multiple remotes since the reference is resolved locally) and I'm sure it's worth it.

It would also be nice to have a column of the user interface show the name of the remote but I need to make the UI more configurable first.

**Comment by sdelafond** [comment]
Working just fine here.

**Comment by nbedos** [comment]
Thanks!
